### PR TITLE
fix(#201): typings

### LINKED ISSUE #201: Wrong types? result should be EntryInfo[], but is typed as string[]
Hello,

with the latest changes the the readdirpPromise method is typed to return only an array of strings:

VSCode says:

```TS
readdirpPromise(root: Path, options?: Partial<ReaddirpOptions>): Promise<string[]>
```

Is this expected?

### PR DESCRIPTION
**Pull request by KillerCodeMonkey**
fix:
- return type of readdirp
- type of filter options
- enum for type option, with fallback for old string type option

fix #201

### CODE REVIEW

**Comment by paulmillr** [comment]
maybe try `const enum` instead. We also can't do breaking changes really

**Comment by KillerCodeMonkey** [comment]
why no breaking changes? just release a new major version?

**Comment by KillerCodeMonkey** [comment]
i mean all the not working typings are "breaking" changes...

**Comment by paulmillr** [comment]
> just release a new major version

no. I do rare releases. Releasing v5 one month after v4 is unnecessary.

>i mean all the not working typings are "breaking" changes...

Yes, so this is a bug fixing, and is OK. For users who did not use `readdirpPromise` we should not break stuff.

File: index.ts [hunk 1]
```diff
@@ -20,38 +20,47 @@ export interface EntryInfo {
...
 const RECURSIVE_ERROR_CODE = 'READDIRP_RECURSIVE_ERROR';
 const NORMAL_FLOW_ERRORS = new Set(['ENOENT', 'EPERM', 'EACCES', 'ELOOP', RECURSIVE_ERROR_CODE]);
-const FILE_TYPE = 'files';
-const DIR_TYPE = 'directories';
-const FILE_DIR_TYPE = 'files_directories';
-const EVERYTHING_TYPE = 'all';
-const ALL_TYPES = [FILE_TYPE, DIR_TYPE, FILE_DIR_TYPE, EVERYTHING_TYPE];
-const DIR_TYPES = new Set([DIR_TYPE, FILE_DIR_TYPE, EVERYTHING_TYPE]);
-const FILE_TYPES = new Set([FILE_TYPE, FILE_DIR_TYPE, EVERYTHING_TYPE]);
+const ALL_TYPES = [EntryTypes.DIR_TYPE, EntryTypes.EVERYTHING_TYPE, EntryTypes.FILE_DIR_TYPE, EntryTypes.FILE_TYPE, 'files', 'directories', 'files_directories', 'all'];
```
Comment (paulmillr) [inline index.ts:56]: this is incorrect

Comment (KillerCodeMonkey) [reply index.ts]: what exactly?

Comment (paulmillr) [reply index.ts]: you're duplicating same entries. `EntryTypes.DIR_TYPE, ..., 'directories'`

Comment (KillerCodeMonkey) [reply index.ts]: yes, because i need to do it for not doing breaking changes. i could hard type the array as "string[]" if you like it more.

File: index.ts [hunk 2]
```diff
@@ -20,38 +20,68 @@ export interface EntryInfo {
...
-    root: '.',
-    fileFilter: (_path: EntryInfo) => true,
-    directoryFilter: (_path: EntryInfo) => true,
-    type: FILE_TYPE,
-    lstat: false,
-    depth: 2147483648,
-    alwaysStat: false,
-    highWaterMark: 4096,
-  };
+export enum EntryTypes {
```
Comment (paulmillr) [inline index.ts:25]: use `const enum` https://ultimatecourses.com/blog/const-enums-typescript

File: index.ts (hunk 1 above)
Comment (KillerCodeMonkey) [reply index.ts]: done

File: index.ts (hunk 2 above)
Comment (KillerCodeMonkey) [reply index.ts]: as you wish

File: index.ts [hunk 3]
```diff
@@ -20,38 +20,60 @@ export interface EntryInfo {
...
+  FILE_TYPE = 'files',
+  DIR_TYPE = 'directories',
+  FILE_DIR_TYPE = 'files_directories',
+  EVERYTHING_TYPE = 'all',
 }
+export type ReaddirpOptions = {
+  root: string;
+  fileFilter?: Predicate;
+  directoryFilter?: Predicate;
+  type?: EntryTypes | 'files' | 'directories' | 'files_directories' | 'all';
```
Comment (paulmillr) [inline index.ts:35]: another duplication

File: index.ts (hunk 1 above)
Comment (KillerCodeMonkey) [reply index.ts]: it would, because you arrays and sets were not typed.. so it will be typed as "EntryTypes". so you need ot pass EntryTypes to the method, which would have led to an breaking change, but now it is fine that way

File: index.ts (hunk 3 above)
Comment (KillerCodeMonkey) [reply index.ts:35]: but then you have the breaking change... it then required you to pass an enum value and not the string value.

Comment (paulmillr) [reply index.ts:35]: thanks for clarification

**Comment by KillerCodeMonkey** [comment]
thanks for the fast response :)

if i had more time, i would get the unit tests up and running again

**Comment by paulmillr** [comment]
@KillerCodeMonkey I have resolved the issue with backwards compat, check out c44446d

**Comment by KillerCodeMonkey** [comment]
sorry some changes are missing there readdirP should return EntryInfo[] and not Path[] what is just a string[].

And in the ReaddirpOptions the root should be optional

**Comment by paulmillr** [comment]
It's string though

https://github.com/paulmillr/readdirp/blob/c44446dc886be85094541110b58f927c3977f8f9/index.ts#L307-L311

**Comment by KillerCodeMonkey** [comment]
but if i log the result of readdirp it gives me a list of EntryInfo[]... and not a list of strings

**Comment by paulmillr** [comment]
e658127

**Comment by KillerCodeMonkey** [comment]
nice and now just mark the `root` option in ReaddirOptions as optional

**Comment by paulmillr** [comment]
Partial<something> makes all fields of something optional.

**Comment by KillerCodeMonkey** [comment]
yes

**Comment by paulmillr** [comment]
So it's already there: `options: Partial<ReaddirpOptions> = {}`

**Comment by KillerCodeMonkey** [comment]
ah then i missed that, sorry

**Comment by KillerCodeMonkey** [comment]
so then i guess it is ready to ship :).

if you like to release a beta version, let me know. I am here to tests it for my purposes with the promise version

**Comment by paulmillr** [comment]
This is not a huge issue, so I will wait for a month or so before doing 4.0.2 with other fixes.

There is no need to release beta. 1. Users can build their own readdirp from github source. 2. Users can override types using `@ts-ignore` and similar stuff for now.

**Comment by paulmillr** [comment]
I follow rare release schedule for supply chain security, it makes it easier for users to verify ocassional releases of my software. If, instead, I was spamming "weekly release", it would have been harder to reason about.

**Comment by KillerCodeMonkey** [comment]
yes yes. it was just an idea.

**Comment by KillerCodeMonkey** [comment]
thanks again :)
